library(ggplot2)
library(tidyverse)
library(ranger)
library(missRanger)
library(data.table)
library(abind)
library(mongolite)

set.seed(52638)

# read the data in and do a bit of cleaning
url <- "https://github.com/dmoste/DATA607/blob/master/Final/all_transcripts.csv?raw=true"
df <- read.csv(url, header = TRUE) %>%
  separate(Table, c("Code","GPA.Modify"), sep = "\\*") %>%
  select(-GPA.Modify,
         -Term.Average.Display,
         -Credits.Total,
         -Credit.Earned.Total,
         -Credits.Average,
         -Credits.Total.1,
         -Cumulative.Term.Average1,
         -Mark.1,
         -Credits.Average.1,
         -Credit.Earned.Total.1,
         -CreditEarned.1,
         -Mark,
         -CreditEarned) %>%
  mutate(College = ifelse(grepl("U$", Code) | Code == "HBS11UA", "Y", "N")) %>%
  tbl_df()

my_collection <- mongo(collection = "attendance", db = "final")
attendance <- my_collection$find('{}')

# StudentID is only listed for the last instance of each student. This section of
# code pulls up that ID number through all the rows of a student. I then converted
# all the course codes into usable names as columns so that the ranger package can
# use them as features later.
df$StudentID <- nafill(df$StudentID, type = "nocb")
df$Code <- make.names(df$Code, unique = FALSE, allow_ = FALSE)

# This makes each course code a feature for ranger and takes the max score a
# student received in a course as the official score.
df <- df %>%
  pivot_wider(names_from  = Code,
              values_from = NumericEquivalent) %>%
  group_by(StudentID) %>%
  left_join(attendance, by = "StudentID") %>%
  summarise_if(is.numeric,
               max,
               na.rm = TRUE)

# In this step, I converted all the -Inf generated by the summarise_if statement
# into NAs so that they could then be imputed by missRanger.
df[df == -Inf] <- NA
df <- df[, which(colMeans(!is.na(df)) > 0.05)]
df <- df %>%
  mutate(Imputed = ifelse(is.na(df$MGS22), 1, 0)) %>%
  select(-TermCD, -SchoolYear)

# Impute missing data
df <- missRanger(df, num.trees = 100, maxiter = 5)

# This step creates the training and holdout datasets for ranger
sample_size = floor(0.75*nrow(df))
picked      = sample(seq_len(nrow(df)),
                     size = sample_size)
training    = df[picked,]
holdout     = df[-picked,]

OOB_RMSE <- vector(mode = "numeric", length = 100)

# Use the best parameter values to create 100 different models
for(i in seq_along(OOB_RMSE)) {
  optimal_ranger <- ranger(
    formula         = MGS22 ~ ., 
    data            = training, 
    num.trees       = 500,
    mtry            = 36,
    min.node.size   = 1,
    sample.fraction = .8,
    importance      = 'impurity')
  OOB_RMSE[i] <- sqrt(optimal_ranger$prediction.error)
}

# View the histogram of the RMSE to confirm normality
hist(OOB_RMSE, breaks = 20)

importance <- data.frame(optimal_ranger$variable.importance)
setDT(importance, keep.rownames = TRUE)[]
names(importance) <- c("Variable", "Value")

# View the most important predictors from the data set
importance %>%
  arrange(desc(Value)) %>%
  top_n(20) %>%
  ggplot(aes(reorder(Variable, Value), Value)) +
  geom_col() +
  coord_flip() +
  ggtitle("Top 20 important variables")

# Run the predictor on the holdout data and plot the results
pred_ranger <- predict(optimal_ranger, holdout)
plot(pred_ranger[["predictions"]], holdout$MGS22)

# Use some statistics knowledge to see how well the model fits the data
m_all <- lm(holdout$MGS22 ~ pred_ranger[["predictions"]])
summary(m_all)
abline(m_all)

# Since some of the data was imputed, let's look at the breakdown of
# real vs imputed data
pf <-data.frame(holdout, pred_ranger[["predictions"]])
pf$Imputed <- as.factor(pf$Imputed)
ggplot(pf,
       aes(x     = pred_ranger...predictions...,
           y     = MGS22,
           color = Imputed)) + geom_point()

# Remove imputed data from the predictions
pf <- filter(pf, Imputed == 0)

# Use some statistics knowledge to see how well the model fits the real data
m_real <- lm(pf$MGS22 ~ pf$pred_ranger...predictions...)
plot(pf$pred_ranger...predictions..., pf$MGS22)
abline(m_real)
summary(m_real)

# Save my amazing model!
saveRDS(optimal_ranger, "big_model.rds")